# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhvZEXO0Pr01LqIhP1u84xx_KwIRJo4I
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date

st.set_page_config(page_title="UPR Calculator | African Actuarial Consultants", layout="wide")

# ---------- CUSTOM CSS for Gold/White/Black theme + corporate layout ----------
st.markdown("""
<style>
    /* Global */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    /* Header / Navigation */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-bottom: 3px solid #D4AF37;
    }
    .logo {
        color: #D4AF37;
        font-size: 1.8rem;
        font-weight: bold;
        text-decoration: none;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.3s;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }
    /* Hero Section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 3rem 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.8rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }
    /* Main content container */
    .main-container {
        max-width: 1400px;
        margin: 2rem auto;
        padding: 0 2rem;
    }
    /* Cards for input/output */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        margin-top: 0;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }
    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }
    /* Streamlit element overrides */
    .stButton > button, .stDownloadButton > button {
        background-color: #D4AF37;
        color: #000000;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: #B8960F;
        color: #FFFFFF;
    }
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 5px;
        padding: 1rem;
    }
    .stTextInput > div > div > input, .stDateInput > div > div > input {
        border: 1px solid #D4AF37;
        border-radius: 4px;
    }
    .dataframe {
        border: 1px solid #D4AF37;
        border-radius: 8px;
        overflow: hidden;
    }
</style>
""", unsafe_allow_html=True)

# ---------- Header (HTML) ----------
st.markdown("""
<div class="header">
    <a href="#" class="logo">AAC</a>
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero Section ----------
st.markdown("""
<div class="hero">
    <h1>Unearned Premium Reserve Calculator</h1>
    <p>Professional UPR calculation tool for insurance professionals. Upload your data, select valuation date, and download results instantly.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Container ----------
st.markdown('<div class="main-container">', unsafe_allow_html=True)

# Two-column layout for inputs and results
col_left, col_right = st.columns([1, 1], gap="large")

with col_left:
    with st.container():
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("### ⚙️ Input Parameters")
        valuation_date = st.date_input("Valuation Date", value=date(2025, 12, 31))
        client_name = st.text_input("Client Name (for file name)", value="Client").strip()
        uploaded_file = st.file_uploader("Choose a CSV file", type="csv")
        st.markdown('</div>', unsafe_allow_html=True)

with col_right:
    with st.container():
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("### 📊 Results")
        if uploaded_file is not None:
            # Placeholder – will be replaced with actual results
            st.info("Upload a file to see results")
        else:
            st.info("Awaiting file upload...")
        st.markdown('</div>', unsafe_allow_html=True)

# If file uploaded, process and display results in the right column
if uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)

        required_cols = [
            'Start_Date', 'End_Date', 'Gross_Premium', 'Reinsurance_Premium',
            'Gross_Commission', 'Reinsurance_Commission', 'Line_Of_Business'
        ]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            st.error(f"Missing columns: {', '.join(missing)}. Please ensure your CSV contains these columns.")
        else:
            df['Start_Date'] = pd.to_datetime(df['Start_Date'])
            df['End_Date'] = pd.to_datetime(df['End_Date'])

            valuation_date_ts = pd.to_datetime(valuation_date)
            df["Duration"] = (df["End_Date"] - df["Start_Date"]).dt.days

            conditions = [
                valuation_date_ts < df["Start_Date"],
                valuation_date_ts > df["End_Date"],
                (valuation_date_ts <= df["End_Date"]) & (valuation_date_ts >= df["Start_Date"])
            ]
            choices = [
                1,
                0,
                ((df["End_Date"] - valuation_date_ts).dt.days) / df["Duration"]
            ]
            df["Unearned_portion"] = np.select(conditions, choices, default=np.nan)

            df["UPR"] = df["Unearned_portion"] * df["Gross_Premium"]
            df["RIUPR"] = df["Unearned_portion"] * df["Reinsurance_Premium"]
            df["GrossDAC"] = df["Unearned_portion"] * df["Gross_Commission"]
            df["RIDAC"] = df["Unearned_portion"] * df["Reinsurance_Commission"]

            result = df.groupby('Line_of_business').agg(
                GrossUPR=('UPR', 'sum'),
                RIUPR=('RIUPR', 'sum'),
                GrossDAC=('GrossDAC', 'sum'),
                RIDAC=('RIDAC', 'sum')
            ).reset_index()

            # Display results in the right column
            with col_right:
                with st.container():
                    st.markdown('<div class="card">', unsafe_allow_html=True)
                    st.markdown("### 📊 Results")
                    st.dataframe(result, use_container_width=True)

                    # Prepare download
                    output = BytesIO()
                    with pd.ExcelWriter(output, engine='openpyxl') as writer:
                        result.to_excel(writer, index=False, sheet_name='UPR_Results')
                    output.seek(0)

                    safe_client = "".join(c for c in client_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
                    if not safe_client:
                        safe_client = "UPR_Results"
                    file_name = f"{safe_client}_UPR_Results.xlsx"

                    st.download_button(
                        label="📥 Download Excel",
                        data=output,
                        file_name=file_name,
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    )
                    st.markdown('</div>', unsafe_allow_html=True)

    except Exception as e:
        st.error(f"An error occurred: {e}")

st.markdown('</div>', unsafe_allow_html=True)  # close main-container

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved. | <a href="#">Privacy</a> | <a href="#">Terms</a></p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">Powered by Streamlit</p>
</div>
""", unsafe_allow_html=True)
