# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bN6aT4oHX2kfjWV7xFpAX5w-tT2fH_Y3
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date

st.set_page_config(page_title="UPR Calculator", layout="centered")
st.title("📊 Unearned Premium Reserve (UPR) Calculator")
st.markdown("Upload your premium schedule CSV file. Select the valuation date and enter a client name. The app will calculate **Gross UPR**, **RI UPR**, **Gross DAC** and **RI DAC** grouped by line of business.")

# --- User inputs ---
col1, col2 = st.columns(2)
with col1:
    valuation_date = st.date_input("Valuation Date", value=date(2025, 12, 31))
with col2:
    client_name = st.text_input("Client Name (for file name)", value="Client").strip()

# Convert valuation_date to pandas Timestamp for consistency
valuation_date = pd.to_datetime(valuation_date)

# File uploader
uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

if uploaded_file is not None:
    try:
        # Read the uploaded CSV
        df = pd.read_csv(uploaded_file)

        # Check for required columns (exact names as in your spec)
        required_cols = [
            'Start_Date', 'End_Date', 'Gross_Premium', 'Reinsurance_Premium',
            'Gross_Commission', 'Reinsurance_Commission', 'Line_Of_Business'
        ]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            st.error(f"Missing columns: {', '.join(missing)}. Please ensure your CSV contains these columns.")
        else:
            # Convert dates
            df['Start_Date'] = pd.to_datetime(df['Start_Date'])
            df['End_Date'] = pd.to_datetime(df['End_Date'])

            # Calculate Duration in days
            df["Duration"] = (df["End_Date"] - df["Start_Date"]).dt.days

            # Calculate Unearned Portion
            conditions = [
                valuation_date < df["Start_Date"],
                valuation_date > df["End_Date"],
                (valuation_date <= df["End_Date"]) & (valuation_date >= df["Start_Date"])
            ]
            choices = [
                1,
                0,
                ((df["End_Date"] - valuation_date).dt.days) / df["Duration"]
            ]
            df["Unearned_portion"] = np.select(conditions, choices, default=np.nan)

            # Calculate UPR, RI UPR, Gross DAC, RI DAC
            df["UPR"] = df["Unearned_portion"] * df["Gross_Premium"]
            df["RIUPR"] = df["Unearned_portion"] * df["Reinsurance_Premium"]
            df["GrossDAC"] = df["Unearned_portion"] * df["Gross_Commission"]
            df["RIDAC"] = df["Unearned_portion"] * df["Reinsurance_Commission"]

            # Aggregate by Line of Business
            result = df.groupby('Line_Of_Business').agg(
                GrossUPR=('UPR', 'sum'),
                RIUPR=('RIUPR', 'sum'),
                GrossDAC=('GrossDAC', 'sum'),
                RIDAC=('RIDAC', 'sum')
            ).reset_index()

            # Display results
            st.subheader("✅ Results")
            st.dataframe(result)

            # Prepare Excel file for download
            output = BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                result.to_excel(writer, index=False, sheet_name='UPR_Results')
            output.seek(0)

            # Create filename with client name
            safe_client = "".join(c for c in client_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
            if not safe_client:
                safe_client = "UPR_Results"
            file_name = f"{safe_client}_UPR_Results.xlsx"

            st.download_button(
                label="📥 Download results as Excel",
                data=output,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

    except Exception as e:
        st.error(f"An error occurred: {e}")
