# -*- coding: utf-8 -*-
"""upr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqK7C2sY-9C9lijRpxf1tPX7m7_oenAv
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date

st.set_page_config(page_title="UPR Calculator", layout="wide")

# ---------- CUSTOM CSS (African Actuarial Consultants theme) ----------
st.markdown("""
<style>
    /* Global */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }
    /* Header / Navigation */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        border-bottom: 3px solid #D4AF37;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.3s;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }
    /* Hero Section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }
    /* Main container */
    .main-container {
        max-width: 1400px;
        margin: 2rem auto;
        padding: 0 2rem;
    }
    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        margin-top: 0;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }
    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }
    /* Streamlit element overrides */
    .stButton > button, .stDownloadButton > button {
        background-color: #D4AF37;
        color: #000000;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: #B8960F;
        color: #FFFFFF;
    }
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 5px;
        padding: 1rem;
    }
    .stMultiSelect [data-baseweb="select"] {
        border: 1px solid #D4AF37;
        border-radius: 4px;
    }
    .dataframe {
        border: 1px solid #D4AF37;
        border-radius: 8px;
        overflow: hidden;
    }
</style>
""", unsafe_allow_html=True)

# ---------- Header ----------
st.markdown("""
<div class="header">
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Unearned Premium Reserve (UPR) Calculator</h1>
    <p>Upload your premiums schedule CSV. Select the valuation date, choose the numeric Columns for which you need the UPR, and enter a client name. The app calculates UPR-equivalent reserves grouped by line of business.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Container ----------
st.markdown('<div class="main-container">', unsafe_allow_html=True)

# --- User inputs ---
col1, col2, col3 = st.columns(3)
with col1:
    valuation_date = st.date_input("Valuation Date", value=date(2025, 12, 31))
with col2:
    client_name = st.text_input("Client Name (for file name)", value="Client").strip()
with col3:
    # empty for spacing
    pass

valuation_date = pd.to_datetime(valuation_date)

# File uploader
uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

if uploaded_file is not None:
    try:
        # Handle encoding
        try:
            df = pd.read_csv(uploaded_file, encoding='utf-8')
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            df = pd.read_csv(uploaded_file, encoding='cp1252')
            st.warning("File read with Windows‑1252 encoding. For best results, save your CSV as UTF‑8.")

        # Drop unnamed columns
        unnamed = [c for c in df.columns if c.startswith('Unnamed:')]
        if unnamed:
            df = df.drop(columns=unnamed)
            st.info(f"Dropped {len(unnamed)} unnamed column(s).")

        # Preview
        with st.expander("Preview of uploaded data"):
            st.dataframe(df.head())

        # Required columns
        required = ['Start_Date', 'End_Date', 'Line_of_business']
        missing = [col for col in required if col not in df.columns]
        if missing:
            st.error(f"Missing required columns: {', '.join(missing)}. Please ensure your CSV contains Start_Date, End_Date, and Line_of_business.")
        else:
            # Convert dates
            df['Start_Date'] = pd.to_datetime(df['Start_Date'], errors='coerce')
            df['End_Date'] = pd.to_datetime(df['End_Date'], errors='coerce')
            if df['Start_Date'].isna().any() or df['End_Date'].isna().any():
                st.error("Some dates could not be parsed. Please check your date columns.")
                st.stop()

            # Calculate Duration in days
            df["Duration"] = (df["End_Date"] - df["Start_Date"]).dt.days
            if (df["Duration"] <= 0).any():
                st.warning("Some policies have zero or negative duration. They will be excluded.")
                df = df[df["Duration"] > 0]

            # Calculate Unearned Portion
            conditions = [
                valuation_date < df["Start_Date"],
                valuation_date > df["End_Date"],
                (valuation_date <= df["End_Date"]) & (valuation_date >= df["Start_Date"])
            ]
            choices = [
                1,
                0,
                ((df["End_Date"] - valuation_date).dt.days) / df["Duration"]
            ]
            df["Unearned_portion"] = np.select(conditions, choices, default=np.nan)

            # Identify numeric columns (excluding dates and Line_of_business)
            exclude = ['Start_Date', 'End_Date', 'Line_of_business', 'Duration', 'Unearned_portion']
            numeric_candidates = [col for col in df.select_dtypes(include=[np.number]).columns if col not in exclude]

            if not numeric_candidates:
                st.error("No numeric columns found to calculate UPR.")
                st.stop()

            # Let user select columns to process
            st.markdown("Select Columns for UPR Calculation")
            default_cols = [c for c in numeric_candidates if c in ['Gross_Premium', 'Reinsurance_premium', 'Gross_Commission', 'Reinsurance_Commission']]
            selected_cols = st.multiselect(
                "Choose the numeric columns (premiums, commissions, etc.) for which you want the UPR:",
                options=numeric_candidates,
                default=default_cols if default_cols else numeric_candidates[:4]
            )

            if not selected_cols:
                st.warning("Please select at least one numeric column.")
                st.stop()

            # Calculate UPR for each selected column
            for col in selected_cols:
                df[f"{col}_UPR"] = df["Unearned_portion"] * df[col]

            # Aggregate by Line of Business
            upr_columns = [f"{col}_UPR" for col in selected_cols]
            result = df.groupby('Line_of_business')[upr_columns].sum().reset_index()

            # Display results
            st.markdown('<div class="card">', unsafe_allow_html=True)
            st.subheader("UPR Results by Line of Business")
            st.dataframe(result, use_container_width=True)
            st.markdown('</div>', unsafe_allow_html=True)

            # Prepare Excel download
            output = BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                result.to_excel(writer, index=False, sheet_name='UPR_Results')
            output.seek(0)

            # Filename with client name
            safe_client = "".join(c for c in client_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
            file_name = f"{safe_client}_UPR_Results.xlsx" if safe_client else "UPR_Results.xlsx"

            st.download_button(
                label="Download results as Excel",
                data=output,
                file_name=file_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

    except Exception as e:
        st.error(f"An error occurred: {e}")

st.markdown('</div>', unsafe_allow_html=True)  # close main-container

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved. | <a href="#">Privacy</a> | <a href="#">Terms</a></p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">Powered by Vanababa</p>
</div>
""", unsafe_allow_html=True)